[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
cpmm = "6nyRQDmzjSqorVVVyFN3AnrqKSS2Lg4UHp3DgnFCAj32"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../owner.json"

[scripts]
generate-clients = "yarn ts-node ./scripts/generate-clients.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
