[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
cpmm = "2wFPV42nma7Lv8fqfUEtzBYGoiZybowLxFokaGGMqGCg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
