name: Anchor
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: backpackapp/build:v0.30.1

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          apt-get update && apt-get install -y openssl libssl-dev

      - name: Set Rust 1.79.0 as default
        run: rustup default 1.79.0

      - name: Generate new keygen
        run: solana-keygen new --no-bip39-passphrase --outfile owner.json

      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899

      - name: Install npm dependencies
        working-directory: amms/
        run: npm install

      - name: Build
        working-directory: amms/
        run: anchor build

      - name: Generate Clients
        working-directory: amms/
        run: anchor run generate-clients

      - name: Check Node.js Crypto API
        run: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"

      - name: Run tests
        working-directory: amms/
        run: node --experimental-global-webcrypto node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'