name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up working directory
      run: cd cpmm/programs/cpmm

    - name: Build
      run: cd cpmm/programs/cpmm && cargo build --verbose

    - name: Run tests
      run: cd cpmm/programs/cpmm && cargo test --verbose

